### ISSUE TITLE
Test watcher failed and throws error

### ISSUE THREAD

**Issue by mohdhazwan** [Wufe/react-particles-js#11]
I'm on Create React App. It uses Jest as its test runner 
Upon run test, this was the error

`TypeError: Cannot read property 'clearRect' of null`

 ```
at e.value (node_modules/react-particles-js/lib/particles.js:604:26)
      at e.value (node_modules/react-particles-js/lib/particles.js:977:214)
      at e.value (node_modules/react-particles-js/lib/particles.js:988:23)
      at e.value (node_modules/react-particles-js/lib/particles.js:1002:48)
      at e.value (node_modules/react-particles-js/lib/particles.js:670:44)
      at t.<anonymous> (node_modules/react-particles-js/lib/particles.js:101:85)
      at CallbackQueue.notifyAll (node_modules/react-dom/lib/CallbackQueue.js:76:22)
      at ReactUpdatesFlushTransaction.close (node_modules/react-dom/lib/ReactUpdates.js:59:24)
      at ReactUpdatesFlushTransaction.closeAll (node_modules/react-dom/lib/Transaction.js:209:25)
      at ReactUpdatesFlushTransaction.perform (node_modules/react-dom/lib/Transaction.js:156:16)
      at ReactUpdatesFlushTransaction.perform (node_modules/react-dom/lib/ReactUpdates.js:89:32)
      at Object.flushBatchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:172:19)
      at ReactDefaultBatchingStrategyTransaction.closeAll (node_modules/react-dom/lib/Transaction.js:209:25)
      at ReactDefaultBatchingStrategyTransaction.perform (node_modules/react-dom/lib/Transaction.js:156:16)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactDefaultBatchingStrategy.js:62:26)
      at Object.batchedUpdates (node_modules/react-dom/lib/ReactUpdates.js:97:27)
      at Object._renderNewRootComponent (node_modules/react-dom/lib/ReactMount.js:319:18)
      at Object._renderSubtreeIntoContainer (node_modules/react-dom/lib/ReactMount.js:401:32)
      at Object.render (node_modules/react-dom/lib/ReactMount.js:422:23)
      at Object.<anonymous>.it (src/App.test.js:7:48)
      at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by model3volution** [comment]
@mohdhazwan I'm using CRA and jest as well but am not able to reproduce your issue.  Can you post your assertion?

**Comment by mastertinner** [comment]
I'm having the exact same problem using CRA. My test file looks as follows:

```javascript
import React from 'react';
import ReactDOM from 'react-dom';
import Radium from 'radium';
import { MemoryRouter } from 'react-router-dom';

import App from './App';

Radium.TestMode.enable();

it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(
      <MemoryRouter>
        <App />
      </MemoryRouter>,
    div,
  );
});
```

**Comment by model3volution** [comment]
Do you mind sharing your `package.json` so we can verify versions.

**Comment by mastertinner** [comment]
Of course.

```
...
"dependencies": {
    "body-parser": "^1.18.2",
    "compression": "^1.7.1",
    "d3-format": "^1.2.0",
    "d3-time-format": "^2.1.0",
    "express": "^4.16.2",
    "history": "^4.7.2",
    "immutable": "^3.8.2",
    "node-fetch": "^1.7.3",
    "node-zendesk": "^1.2.0",
    "prop-types": "^15.6.0",
    "radium": "^0.19.6",
    "react": "^16.1.1",
    "react-async-script": "^0.9.1",
    "react-dom": "^16.1.1",
    "react-google-recaptcha": "^0.9.7",
    "react-particles-js": "^2.1.0",
    "react-redux": "^5.0.6",
    "react-router-dom": "^4.2.2",
    "react-router-redux": "^5.0.0-alpha.8",
    "react-scripts": "^1.0.17",
    "react-select": "^1.0.0-rc.10",
    "redux": "^3.7.2",
    "winston": "^2.4.0",
    "xhr": "^2.4.0"
  },
  "devDependencies": {
    "nightwatch": "^0.9.16"
  },
...
```
