### ISSUE TITLE
tsparticles (not foced to v1.17.1) breaks build on Vercel

### ISSUE THREAD

**Issue by exocode** [Wufe/react-particles-js#154]
Hi there I dont know where to address this issue, but when I install `react-particles-js` without installing `npm i --save tsparticles@1.17.1` my build breaks with `MODULE_NOT_FOUND`. So when `tsparticles@1.18.x`is running the build breaks. I didnt tried other versions higher than 1.17.1 but with this it is working. 
My page is a Gatsby page (a Static site generator).

```shell

01:37:16.022 | Cloning completed in 12921ms
-- | --
01:37:16.024 | Analyzing source code...
01:37:19.629 | Installing build runtime...
01:37:20.156 | Build runtime installed: 526.990ms
01:37:20.659 | Looking up build cache...
01:37:21.083 | Installing build runtime...
01:37:21.093 | Build cache found. Downloading...
01:37:21.679 | Build runtime installed: 596.273ms
01:37:22.560 | Looking up build cache...
01:37:22.922 | Build cache not found
01:37:22.959 | Installing build runtime...
01:37:23.787 | Build runtime installed: 835.225ms
01:37:23.826 | Installing dependencies...
01:37:24.608 | Looking up build cache...
01:37:24.972 | Build cache not found
01:37:25.903 | Installing dependencies...
01:37:35.149 | Build cache downloaded [335.36 MB]: 14054.67ms
01:37:35.724 | Installing dependencies...
01:38:25.526 | > bufferutil@4.0.1 install /vercel/workpath1/node_modules/bufferutil
01:38:25.526 | > node-gyp-build
01:38:26.104 | > tsparticles@1.18.4 install /vercel/workpath1/node_modules/tsparticles
01:38:26.104 | > node ./scripts/install.js
01:38:26.177 | internal/modules/cjs/loader.js:968
01:38:26.177 | throw err;
01:38:26.177 | ^
01:38:26.178 | Error: Cannot find module '/vercel/workpath1/api/package.json'
01:38:26.178 | Require stack:
01:38:26.178 | - /vercel/workpath1/node_modules/tsparticles/scripts/install.js
01:38:26.178 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
01:38:26.178 | at Function.Module._load (internal/modules/cjs/loader.js:841:27)
01:38:26.178 | at Module.require (internal/modules/cjs/loader.js:1025:19)
01:38:26.178 | at require (internal/modules/cjs/helpers.js:72:18)
01:38:26.178 | at Object.<anonymous> (/vercel/workpath1/node_modules/tsparticles/scripts/install.js:2:21)
01:38:26.178 | at Module._compile (internal/modules/cjs/loader.js:1137:30)
01:38:26.178 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
01:38:26.178 | at Module.load (internal/modules/cjs/loader.js:985:32)
01:38:26.178 | at Function.Module._load (internal/modules/cjs/loader.js:878:14)
01:38:26.178 | at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
01:38:26.178 | code: 'MODULE_NOT_FOUND',
01:38:26.178 | requireStack: [ '/vercel/workpath1/node_modules/tsparticles/scripts/install.js' ]
01:38:26.178 | }
01:38:28.803 | npm WARN The package node-sass is included as both a dev and production dependency.
01:38:28.811 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
01:38:28.811 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
01:38:28.818 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
01:38:28.818 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
01:38:28.824 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/babel-plugin-add-module-exports/node_modules/fsevents):
01:38:28.824 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
01:38:28.829 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
01:38:28.829 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
01:38:28.977 | npm ERR! code ELIFECYCLE
01:38:28.977 | npm ERR! errno 1
01:38:28.979 | npm ERR! tsparticles@1.18.4 install: `node ./scripts/install.js`
01:38:28.979 | npm ERR! Exit status 1
01:38:28.979 | npm ERR!
01:38:28.979 | npm ERR! Failed at the tsparticles@1.18.4 install script.
01:38:28.979 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
01:38:29.019 | npm ERR! A complete log of this run can be found in:
01:38:29.019 | npm ERR!     /vercel/.npm/_logs/2020-10-16T23_38_29_003Z-debug.log
01:38:29.050 | Error: Command "npm install" exited with 1
01:39:16.330 | > bufferutil@4.0.1 install /vercel/workpath0/node_modules/bufferutil
01:39:16.330 | > node-gyp-build
01:39:16.904 | > tsparticles@1.18.4 install /vercel/workpath0/node_modules/tsparticles
01:39:16.904 | > node ./scripts/install.js
01:39:16.980 | internal/modules/cjs/loader.js:968
01:39:16.980 | throw err;
01:39:16.980 | ^
01:39:16.981 | Error: Cannot find module '/vercel/workpath0/api/package.json'
01:39:16.981 | Require stack:
01:39:16.981 | - /vercel/workpath0/node_modules/tsparticles/scripts/install.js
01:39:16.981 | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
01:39:16.981 | at Function.Module._load (internal/modules/cjs/loader.js:841:27)
01:39:16.981 | at Module.require (internal/modules/cjs/loader.js:1025:19)
01:39:16.981 | at require (internal/modules/cjs/helpers.js:72:18)
01:39:16.981 | at Object.<anonymous> (/vercel/workpath0/node_modules/tsparticles/scripts/install.js:2:21)
01:39:16.981 | at Module._compile (internal/modules/cjs/loader.js:1137:30)
01:39:16.981 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
01:39:16.981 | at Module.load (internal/modules/cjs/loader.js:985:32)
01:39:16.981 | at Function.Module._load (internal/modules/cjs/loader.js:878:14)
01:39:16.981 | at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
01:39:16.981 | code: 'MODULE_NOT_FOUND',
01:39:16.981 | requireStack: [ '/vercel/workpath0/node_modules/tsparticles/scripts/install.js' ]
01:39:16.981 | }


```

**Comment by matteobruni** [comment]
Hi @exocode,

I'll have a look at that error ASAP, it seems that the install script needs some `try...catch` block.

Could you try with version 1.18.3? It doesn't have that script

**Comment by exocode** [comment]
Nice,.. yes 1.18.3 seems to be able to build: 


```shell

17:26:42.834 | Cloning completed in 13707ms
-- | --
17:26:42.836 | Analyzing source code...
17:26:44.970 | Installing build runtime...
17:26:45.459 | Build runtime installed: 489.291ms
17:26:45.957 | Looking up build cache...
17:26:46.089 | Installing build runtime...
17:26:46.104 | Build cache found. Downloading...
17:26:46.732 | Build runtime installed: 642.595ms
17:26:47.403 | Looking up build cache...
17:26:47.486 | Build cache found. Downloading...
17:26:47.520 | Installing build runtime...
17:26:48.096 | Build runtime installed: 575.768ms
17:26:48.719 | Looking up build cache...
17:26:48.860 | Build cache found. Downloading...
17:26:54.920 | Build cache downloaded [113.25 MB]: 8815.288ms
17:26:55.688 | Installing dependencies...
17:26:57.059 | Build cache downloaded [113.25 MB]: 9572.449ms
17:26:57.841 | Installing dependencies...
17:27:02.619 | Build cache downloaded [338.84 MB]: 13758.502ms
17:27:03.094 | Installing dependencies...
17:27:11.371 | npm WARN @turist/fetch@7.1.7 requires a peer of node-fetch@2 but none is installed. You must install peer dependencies yourself.
17:27:11.373 | npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
17:27:11.375 | npm WARN relay-compiler@10.0.1 requires a peer of graphql@^15.0.0 but none is installed. You must install peer dependencies yourself.
17:27:11.377 | npm WARN The package node-sass is included as both a dev and production dependency.
17:27:11.380 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/babel-plugin-add-module-exports/node_modules/fsevents):
17:27:11.380 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
17:27:11.382 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
17:27:11.382 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
17:27:11.385 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
17:27:11.385 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
17:27:11.387 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
17:27:11.387 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
17:27:11.388 | updated 1 package in 14.704s
17:27:12.946 | 217 packages are looking for funding
17:27:12.946 | run `npm fund` for details
17:27:13.521 | Uploading build outputs...
17:27:25.951 | npm WARN @turist/fetch@7.1.7 requires a peer of node-fetch@2 but none is installed. You must install peer dependencies yourself.
17:27:25.953 | npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
17:27:25.955 | npm WARN relay-compiler@10.0.1 requires a peer of graphql@^15.0.0 but none is installed. You must install peer dependencies yourself.
17:27:25.957 | npm WARN The package node-sass is included as both a dev and production dependency.
17:27:25.959 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/babel-plugin-add-module-exports/node_modules/fsevents):
17:27:25.959 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
17:27:25.962 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
17:27:25.962 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
17:27:25.964 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
17:27:25.965 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
17:27:25.967 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
17:27:25.967 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
17:27:25.968 | updated 1 package in 12.54s
17:27:27.415 | 217 packages are looking for funding
17:27:27.415 | run `npm fund` for details
17:27:28.325 | Uploading build outputs...
17:27:29.263 | Done with "api/contact-form.js"
17:27:40.041 | npm WARN @turist/fetch@7.1.7 requires a peer of node-fetch@2 but none is installed. You must install peer dependencies yourself.
17:27:40.043 | npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
17:27:40.045 | npm WARN relay-compiler@10.0.1 requires a peer of graphql@^15.0.0 but none is installed. You must install peer dependencies yourself.
17:27:40.046 | npm WARN The package node-sass is included as both a dev and production dependency.
17:27:40.049 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/babel-plugin-add-module-exports/node_modules/fsevents):
17:27:40.049 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
17:27:40.051 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
17:27:40.052 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
17:27:40.054 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/webpack-dev-server/node_modules/fsevents):
17:27:40.054 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
17:27:40.056 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/watchpack-chokidar2/node_modules/fsevents):
17:27:40.056 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
17:27:40.057 | updated 1 package in 12.158s
17:27:41.469 | 217 packages are looking for funding
17:27:41.469 | run `npm fund` for details
17:27:43.976 | success open and validate gatsby-configs - 0.115s
17:27:45.108 | success load plugins - 1.088s
17:27:45.113 | Adding mailgo...
17:27:45.153 | success onPreInit - 0.044s
17:27:45.161 | success delete html and css files from previous builds - 0.008s
17:27:45.164 | info One or more of your plugins have changed since the last time you ran Gatsby. As
17:27:45.164 | a precaution, we're deleting your site's cache to ensure there's no stale data.
17:27:45.251 | success initialize cache - 0.090s
17:27:45.270 | success copy gatsby files - 0.018s
17:27:45.282 | success onPreBootstrap - 0.012s
17:27:45.324 | success createSchemaCustomization - 0.005s
17:27:45.718 | Slugify string: Backend
17:27:45.718 | Slugify string: SaaS
17:27:45.719 | Slugify string: React
17:27:45.719 | Slugify string: React Native
17:27:45.719 | Slugify string: iOS / Swift
17:27:45.720 | Slugify string: Shopify
17:27:45.720 | Slugify string: Snipcart
17:27:45.720 | Slugify string: WooCommerce
17:27:45.720 | Slugify string: Virtuemart
17:27:45.720 | Slugify string: Individuell
17:27:45.721 | Slugify string: Ganzheitlich
17:27:45.721 | Slugify string: Kubernetes
17:27:45.721 | Slugify string: Cloud Computing
17:27:45.721 | Slugify string: Poster
17:27:45.721 | Slugify string: Flyer
17:27:45.722 | Slugify string: Logo
17:27:45.762 | Slugify string: Design
17:27:45.762 | Slugify string: Design
17:27:45.763 | Slugify string: Design
17:27:45.763 | Slugify string: Design
17:27:45.763 | Slugify string: Design
17:27:45.763 | Slugify string: Design
17:27:45.764 | Slugify string: Web
17:27:45.764 | Slugify string: Web
17:27:45.764 | Slugify string: Design
17:27:45.764 | Slugify string: Development
17:27:45.764 | Slugify string: Concept
17:27:45.764 | Slugify string: Conception
17:27:45.764 | Slugify string: Web
17:27:45.764 | Slugify string: Audio
17:27:45.765 | Slugify string: Web
17:27:45.765 | Slugify string: Web
17:27:45.765 | Slugify string: Design
17:27:45.931 | Slugify string: Privat
17:27:45.931 | Slugify string: Post
17:27:45.931 | Slugify string: Allgemein
17:27:45.953 | Slugify string: Ian Dee Grees
17:27:45.953 | Slugify string: Raw
17:27:45.953 | Slugify string: Unofficial
17:27:45.954 | Slugify string: Not released yet
17:27:45.954 | Slugify string: Ian Dee Grees
17:27:45.954 | Slugify string: Single EP
17:27:45.954 | Slugify string: Ian Dee Grees
17:27:45.955 | Slugify string: Single EP
17:27:46.026 | Slugify string: Kamera
17:27:46.026 | Slugify string: Schnitt
17:27:46.026 | Slugify string: Initiativ Arbeit
17:27:46.026 | Slugify string: Veranstalter
17:27:46.026 | Slugify string: 100 Gratis CDs
17:27:46.026 | Slugify string: Visuals
17:27:46.026 | Slugify string: DJ Performance
17:27:46.027 | Slugify string: Zeitlich gesteuerte Visuals
17:27:46.027 | Slugify string: Generierte Titel
17:27:46.027 | Slugify string: Live Performance
17:27:46.027 | Slugify string: DJ
17:27:46.027 | Slugify string: Silvester DJ
17:27:46.027 | Slugify string: mit DJ Smoove
17:27:46.028 | Slugify string: DJ JoeJoe
17:27:46.028 | Slugify string: 3D Mapping
17:27:46.028 | Slugify string: 7 Beamer
17:27:46.028 | Slugify string: Musikgesteuerte Performance
17:27:46.028 | Slugify string: Live Video
17:27:47.295 | success Checking for changed pages - 0.000s
17:27:47.295 | success source and transform nodes - 1.971s
17:27:47.761 | success building schema - 0.465s
17:27:47.815 | Slugify string: Post
17:27:47.835 | Slugify string: Privat
17:27:47.835 | Slugify string: Allgemein
17:27:47.839 | info Total nodes: 404, SitePage nodes: 12 (use --verbose for breakdown)
17:27:47.839 | success createPages - 0.077s
17:27:47.839 | success Checking for changed pages - 0.000s
17:27:47.985 | success createPagesStatefully - 0.145s
17:27:47.988 | success Cleaning up stale page-data - 0.002s
17:27:48.014 | success update schema - 0.025s
17:27:48.015 | success onPreExtractQueries - 0.000s
17:27:48.943 | success extract queries from components - 0.927s
17:27:48.947 | success write out redirect data - 0.001s
17:27:52.005 | success Build manifest and related icons - 3.056s
17:27:52.005 | success onPostBootstrap - 3.058s
17:27:52.006 | info bootstrap finished - 10.294s
17:27:52.199 | warning You can't use childImageSharp together with 1.md — use publicURL instead. The childImageSharp portion of the query in this file will return null:
17:27:52.199 | undefined
17:27:52.199 | warning You can't use childImageSharp together with 2.md — use publicURL instead. The childImageSharp portion of the query in this file will return null:
17:27:52.199 | undefined
17:27:52.199 | warning You can't use childImageSharp together with 3.md — use publicURL instead. The childImageSharp portion of the query in this file will return null:
17:27:52.199 | undefined
17:27:52.200 | warning You can't use childImageSharp together with 4.md — use publicURL instead. The childImageSharp portion of the query in this file will return null:
17:27:52.200 | undefined
17:27:54.497 | success run static queries - 2.485s - 20/20 8.05/s
17:27:54.709 | success run page queries - 0.212s - 21/21 99.23/s
17:27:54.713 | success write out requires - 0.004s
17:29:04.635 | warning chunk styles [mini-css-extract-plugin]
17:29:04.635 | Conflicting order. Following module has been added:
17:29:04.635 | * css ./node_modules/css-loader??ref--11-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/animated-background/animated-background-dot.css
17:29:04.635 | despite it was not able to fulfill desired ordering with these modules:
17:29:04.635 | * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-3!./node_modules/sass-loader/dist/cjs.js??ref--12-oneOf-1-3!./src/components/hero/hero.scss
17:29:04.635 | - couldn't fulfill desired order of chunk group(s) component---src-pages-home-js, component---src-pages-index-jsx
17:29:04.635 | * css ./node_modules/css-loader??ref--11-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/scroll-navigation/scroll-navigation.css
17:29:04.635 | - couldn't fulfill desired order of chunk group(s) component---src-pages-home-js, component---src-pages-index-jsx
17:29:04.635 | * css ./node_modules/css-loader??ref--11-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/footer/footer.css
17:29:04.635 | - couldn't fulfill desired order of chunk group(s) component---src-pages-home-js, component---src-pages-index-jsx
17:29:04.635 | warning chunk styles [mini-css-extract-plugin]
17:29:04.635 | Conflicting order. Following module has been added:
17:29:04.635 | * css ./node_modules/css-loader??ref--11-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/footer/footer.css
17:29:04.635 | despite it was not able to fulfill desired ordering with these modules:
17:29:04.635 | * css ./node_modules/css-loader??ref--11-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/get-in-touch/get-in-touch.css
17:29:04.635 | - couldn't fulfill desired order of chunk group(s) component---src-pages-services-jsx
17:29:04.635 | - while fulfilling desired order of chunk group(s) component---src-pages-home-js, component---src-pages-index-jsx, component---src-pages-music-jsx, component---src-pages-projects-jsx, component---src-templates-blog-category-jsx, component---src-templates-blog-list-jsx, component---src-templates-blog-post-jsx, component---src-templates-blog-tags-jsx
17:29:04.635 | * css ./node_modules/css-loader??ref--11-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/blog/blog-list.css
17:29:04.635 | - couldn't fulfill desired order of chunk group(s) component---src-templates-blog-category-jsx, component---src-templates-blog-list-jsx, component---src-templates-blog-tags-jsx
17:29:04.635 | * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-3!./node_modules/sass-loader/dist/cjs.js??ref--12-oneOf-1-3!./src/components/share-content/share-content.scss
17:29:04.635 | - couldn't fulfill desired order of chunk group(s) component---src-templates-blog-category-jsx, component---src-templates-blog-list-jsx, component---src-templates-blog-tags-jsx
17:29:04.635 | - while fulfilling desired order of chunk group(s) component---src-pages-home-js, component---src-pages-index-jsx
17:29:04.635 | * css ./node_modules/css-loader??ref--11-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/slider-carousel/slider-carousel.css
17:29:04.635 | - couldn't fulfill desired order of chunk group(s) component---src-templates-blog-post-jsx
17:29:04.636 | - while fulfilling desired order of chunk group(s) component---src-pages-home-js, component---src-pages-index-jsx
17:29:04.636 | * css ./node_modules/css-loader??ref--11-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/slider-carousel/slide.css
17:29:04.636 | - couldn't fulfill desired order of chunk group(s) component---src-templates-blog-post-jsx
17:29:04.636 | - while fulfilling desired order of chunk group(s) component---src-pages-home-js, component---src-pages-index-jsx
17:29:04.636 | warning chunk styles [mini-css-extract-plugin]
17:29:04.636 | Conflicting order. Following module has been added:
17:29:04.636 | * css ./node_modules/css-loader??ref--11-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/get-in-touch/get-in-touch.css
17:29:04.636 | despite it was not able to fulfill desired ordering with these modules:
17:29:04.636 | * css ./node_modules/css-loader??ref--11-oneOf-1-1!./node_modules/postcss-loader/src??postcss-2!./src/components/blog/blog-list.css
17:29:04.636 | - couldn't fulfill desired order of chunk group(s) component---src-templates-blog-category-jsx, component---src-templates-blog-list-jsx, component---src-templates-blog-tags-jsx
17:29:04.636 | * css ./node_modules/css-loader??ref--12-oneOf-1-1!./node_modules/postcss-loader/src??postcss-3!./node_modules/sass-loader/dist/cjs.js??ref--12-oneOf-1-3!./src/components/share-content/share-content.scss
17:29:04.636 | - couldn't fulfill desired order of chunk group(s) component---src-templates-blog-category-jsx, component---src-templates-blog-list-jsx, component---src-templates-blog-tags-jsx
17:29:04.636 | - while fulfilling desired order of chunk group(s) component---src-pages-home-js, component---src-pages-index-jsx
17:29:04.637 | success Building production JavaScript and CSS bundles - 69.919s
17:29:04.839 | success Rewriting compilation hashes - 0.001s
17:29:18.415 | success Building static HTML for pages - 13.395s - 21/21 1.57/s
17:29:18.486 | info Minify HTML files at public directory, total HTML files 21:
17:29:24.612 | public/404.html > reduced 0.27%.
17:29:24.612 | public/Allgemein/willkommen/index.html > reduced 0.28%.
17:29:24.613 | public/blog/index.html > reduced 0.29%.
17:29:24.613 | public/category/allgemein/index.html > reduced 0.30%.
17:29:24.613 | public/404/index.html > reduced 0.27%.
17:29:24.614 | public/contact/index.html > reduced 0.27%.
17:29:24.615 | public/coming-soon/index.html > reduced 0.27%.
17:29:24.616 | public/design/fm4-unlimited/fm4-unlimited/index.html > reduced 0.27%.
17:29:24.617 | public/design/rumpelstaenzchen/rumpelstänzchen/index.html > reduced 0.27%.
17:29:24.618 | public/design/tune-club/tune-club/index.html > reduced 0.27%.
17:29:24.618 | public/music/index.html > reduced 0.28%.
17:29:24.619 | public/projects/index.html > reduced 0.27%.
17:29:24.619 | public/services/index.html > reduced 0.29%.
17:29:24.621 | public/tags/post/index.html > reduced 0.29%.
17:29:24.622 | public/tags/privat/index.html > reduced 0.29%.
17:29:24.623 | public/visuals-vj-vitamin-d/index.html > reduced 0.28%.
17:29:24.623 | public/web/global-nights/global-nights/index.html > reduced 0.27%.
17:29:24.624 | public/web/room21/room21/index.html > reduced 0.27%.
17:29:24.625 | public/web/sufers-roots/sufers-roots/index.html > reduced 0.27%.
17:29:24.627 | public/index.html > reduced 0.42%.
17:29:24.627 | public/home/index.html > reduced 0.42%.
17:29:24.627 | info Minify HTML files done in 6.142 sec
17:29:34.725 | info Brotli compressed 48 files - 9.996s - 1.105/s
17:29:34.725 | success onPostBuild - 16.310s
17:29:34.730 | info Done building in 113.017874812 sec
17:29:37.552 | Uploading build outputs...
17:30:09.822 | Build completed. Populating build cache...
17:30:43.983 | Uploading build cache [113.28 MB]...
17:30:45.789 | Build cache uploaded: 1804.983ms
17:30:45.808 | Done with "api/test.js"
17:30:46.212 | Build completed. Populating build cache...
17:31:25.699 | Uploading build cache [338.98 MB]...
17:31:30.597 | Build cache uploaded: 4897.193ms
17:31:30.628 | Done with "package.json"


```

**Comment by matteobruni** [comment]
The `1.18.5` version with the fix will be released soon, thanks for the report

**Comment by jspanther** [comment]
Hi, is there any update regarding this? As it breaks down the layout on my production server

**Comment by matteobruni** [comment]
You can update the `tsparticles` dependency to version `1.18.8`

**Comment by matteobruni** [comment]
I've updated `tsParticles` to `1.18.10` with some fixes if you want to try an updated version
